---
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    nobest: True
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat'
  tags: install

- name: Install required packages
  ansible.builtin.package:
    name:
      - ansible-core
      - gcc
      - git-core
      - make
      - podman
      - python3
      - python3-pip
    state: latest
  become: yes
  tags: install

- name: Install some extra packages
  ansible.builtin.package:
    name:
      - bash-completion
      - tmux
      - vim
    state: latest
  become: yes
  tags: install

- name: Pip install openstack client packages as user
  ansible.builtin.pip:
    name:
      - python-openstackclient
      - python-octaviaclient
    extra_args: --user
  tags: install

- name: Clone operators using Git
  ansible.builtin.git: "{{ item }}"
  with_items: "{{ operators_git_repos }}"
  tags: git

- name: Create ~/install_yamls/devsetup/pull-secret.txt
  template:
    src: pull-secret.txt.j2
    dest: "~/install_yamls/devsetup/pull-secret.txt"
  tags: [crc, pull-secret]

#- name: Create devsetup using make (may take 30 minutes or more)
#  shell:
#    cmd: "{{ item }}"
#    chdir: "~/install_yamls/devsetup"
#  with_items:
#    - make crc_cleanup
#      # for some reason this fails
#    - "CPUS={{ make_crc_cpus }} MEMORY={{ make_crc_memory }} make crc"
#    - make download_tools
#  tags: crc

- name: Deploy openstack
  shell:
    cmd: |
      set +ex
      eval $(crc oc-env)
      make crc_storage
      sleep 20
      make input
      make openstack
      sleep 10
      make openstack_deploy
    chdir: "~/install_yamls"
  tags: crc

- name: Create symbolic link for kubectl
  file:
    src: ~/.crc/bin/oc/oc
    dest: ~/.crc/bin/oc/kubectl
    state: link
  tags: crc

- name: Create devsetup using make
  shell:
    cmd: |
      set +ex
      eval $(crc oc-env)
      oc login -u kubeadmin -p 12345678 https://api.crc.testing:6443
      make crc_storage
      make input
      make openstack
      for i in mariadb keystone ovn neutron rabbitmq ; do \
        make $i
        sleep 60
        make ${i}_deploy
      done
      oc completion bash | sudo tee /etc/bash_completion.d/oc_completion
      openstack complete | sudo tee /etc/bash_completion.d/osc.bash_completion
      exit 0
    creates: "/etc/bash_completion.d/oc_completion"
    chdir: "~/install_yamls"
  tags: crc

- name: Ensure ~/.config/openstack/ exists
  file:
    path: ~/.config/openstack
    state: directory
  tags: cloudyaml

- name: Set up ~/.config/openstack/clouds.yaml
  copy:
    src: clouds.yaml
    dest: ~/.config/openstack/clouds.yaml
  tags: cloudyaml

- name: Export OS_CLOUD and OS_PASSWORD in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - export PATH=$PATH:~/.crc/bin/oc
    - export OS_CLOUD=default
    - export OS_PASSWORD=12345678
  tags: tools

- name: Copy ~/.vscode jsons
  copy:
    src: "{{ item }}"
    dest: ~/.vscode/
    force: no
  with_items:
    - launch.json
    - tasks.json
  tags: tools

- name: Increase max_user_watches for VSCode
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=524288
  notify: "Apply sysctl"
  tags: tools

- name: Deploy CRD, build and push Octavia Operator image
  shell:
    cmd: |
      set +ex
      eval $(crc oc-env)
      make generate
      make manifests
      go mod tidy
      oc apply -f ~/octavia-operator/config/crd/bases/octavia.openstack.org_octaviaapis.yaml
      podman rmi -f $(podman images --filter="reference=*octavia*" -q)
      podman login -u {{ podman_dockerio_user }} -p \
        {{ podman_dockerio_password }} docker.io
      podman login -u {{ podman_quayio_user }} -p \
        {{ podman_quayio_password }} quay.io
      podman pull docker.io/library/golang:1.18
      IMAGE_TAG_BASE=quay.io/tweining/octavia-operator VERSION=0.0.1 \
        IMG=$IMAGE_TAG_BASE:v$VERSION make \
        manifests build docker-build docker-push bundle bundle-build \
        bundle-push catalog-build catalog-push
    chdir: "~/octavia-operator"
  tags: image

- name: Prepare for running Octavia Operator locally
  shell:
    cmd: |
      set +ex
      eval $(crc oc-env)
      oc login -u kubeadmin -p 12345678 https://api.crc.testing:6443
      # Uses the official upstream image!
      make octavia
      sleep 10
      make octavia_deploy
      sleep 50
      oc patch csv octavia-operator.v0.0.1 --type json -p='[{"op": "remove", "path": "/spec/install/spec/deployments/0"}]'
      oc delete deployment octavia-operator-controller-manager
    chdir: "~/install_yamls"
  tags: octavia-prep

# Now run the operator as a Go program locally (outside the Kubernetes cluster):
# cd ~/octavia-operator; OPERATOR_TEMPLATES=./templates make install run
